#!/usr/bin/env bash

options="⏻ Shutdown\n Reboot\n⏾ Suspend\n Lock\n󰍃 Logout"

choice=$(echo -e "$options" | rofi -dmenu -p "Power")

case "$choice" in
  *Shutdown) systemctl poweroff ;;
  *Reboot) systemctl reboot ;;
  *Suspend) systemctl suspend ;;
  *Lock) hyprlock ;;
  *Logout) hyprctl dispatch exit ;;
esac

