#!/usr/bin/env bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$DIR/../branding/lib.sh"

# Open processed image in an editor, save to file, notify, and clean up.
# Args: <processed.png> <output.png>
edit() {
  local processed="$1" file="$2"
  swappy -f "$processed" -o "$file"
  [[ -f "$file" ]] && notify-send "Screenshot saved" "$file"
  rm -f "$processed"
}

[[ "${BASH_SOURCE[0]}" != "${0}" ]] && return

options="🖼 Fullscreen [Branded]\n🔲 Select Region [Branded]\n🪟 Window [Branded]\n🖼 Fullscreen\n🔲 Select Region\n🪟 Window\n❌ Cancel"
choice=$(echo -e "$options" | rofi -dmenu -p "Screenshot")
file=~/Pictures/Screenshots/screenshot_$(date +%Y%m%d_%H%M%S).png

case "$choice" in
  "🖼 Fullscreen [Branded]")
    tmpfile=$(mktemp /tmp/screenshot_XXXXXX.png)
    processed=$(mktemp /tmp/screenshot_XXXXXX.png)
    grim "$tmpfile"
    round_corners "$tmpfile"
    add_gradient_bg "$tmpfile" "$processed"
    rm "$tmpfile"
    add_branding "$processed"
    edit "$processed" "$file"
    ;;
  "🔲 Select Region [Branded]")
    tmpfile=$(mktemp /tmp/screenshot_XXXXXX.png)
    processed=$(mktemp /tmp/screenshot_XXXXXX.png)
    grim -g "$(slurp)" "$tmpfile"
    round_corners "$tmpfile"
    add_gradient_bg "$tmpfile" "$processed"
    rm "$tmpfile"
    add_branding "$processed"
    edit "$processed" "$file"
    ;;
  "🪟 Window [Branded]")
    tmpfile=$(mktemp /tmp/screenshot_XXXXXX.png)
    processed=$(mktemp /tmp/screenshot_XXXXXX.png)
    win=$(hyprctl activewindow -j | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')
    grim -g "$win" "$tmpfile"
    round_corners "$tmpfile"
    add_gradient_bg "$tmpfile" "$processed"
    rm "$tmpfile"
    add_branding "$processed"
    edit "$processed" "$file"
    ;;
  "🖼 Fullscreen")
    tmpfile=$(mktemp /tmp/screenshot_XXXXXX.png)
    grim "$tmpfile"
    edit "$tmpfile" "$file"
    ;;
  "🔲 Select Region")
    tmpfile=$(mktemp /tmp/screenshot_XXXXXX.png)
    grim -g "$(slurp)" "$tmpfile"
    edit "$tmpfile" "$file"
    ;;
  "🪟 Window")
    tmpfile=$(mktemp /tmp/screenshot_XXXXXX.png)
    win=$(hyprctl activewindow -j | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')
    grim -g "$win" "$tmpfile"
    round_corners "$tmpfile"
    edit "$tmpfile" "$file"
    ;;
  *Cancel)
    exit 0
    ;;
esac
