$font = JetBrainsMono Nerd Font Mono

general {
    hide_cursor = true
    grace = 0
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
}

background {
    monitor =
    color = rgba(1f2335ff)
}

# TIME
label {
    monitor =
    text = <span letter_spacing="6144">$TIME</span>
    format = %H:%M
    font_size = 72
    font_family = $font
    color = rgba(c0caf5ff)
    position = 0, 80
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] printf '<span letter_spacing="4096">%s</span>' "$(date +'%A, %d %B %Y' | tr '[:lower:]' '[:upper:]')"
    font_size = 12
    font_family = $font
    color = rgba(565f89ff)
    position = 0, 20
    halign = center
    valign = center
}

# PASSWORD INPUT
input-field {
    monitor =
    size = 250, 40
    outline_thickness = 2
    inner_color = rgba(1f2335ff)

    outer_color = rgba(3b4261ff)
    check_color = rgba(7aa2f7ff)
    fail_color = rgba(f7768eff)
    capslock_color = rgba(7aa2f7ff)
    fail_text = $PAMFAIL

    font_color = rgba(c0caf5ff)
    font_family = $font
    placeholder_text = # intentionally empty — label below replaces placeholder
    fade_on_empty = false
    rounding = 0

    dots_center = true
    dots_rounding = -1
    dots_spacing = 0.3

    position = 0, -40
    halign = center
    valign = center
}

# PASSWORD LABEL
label {
    monitor =
    text = PASSWORD
    font_size = 9
    font_family = $font
    color = rgba(3b4261ff)
    position = 0, -85
    halign = center
    valign = center
}
